version: '3'

services:
    api:
        container_name: realworld-docker-api
        build: ./api
        command: npm run start:prod
        restart: unless-stopped
        environment:
            - PORT=3001
            - HOST=http://realworld-docker.com
            - MONGO_URL=mongodb://api_db:27017/api
            - AUTH_API_URL=http://auth:3002/api
        depends_on:
            - api_db
        networks:
            realworld-docker-network:

    api_db:
        container_name: realworld-docker-api-db
        image: mongo:latest
        volumes:
            - mongodb_api:/data/db
        networks:
            realworld-docker-network:

    auth:
        container_name: realworld-docker-auth
        build: ./auth
        command: npm run start:prod
        restart: unless-stopped
        environment:
            - PORT=3002
            - HOST=http://realworld-docker.com
            - MONGO_URL=mongodb://auth_db:27017/auth
            - API_URL=http://api:3001/api
        depends_on:
            - auth_db
        networks:
            realworld-docker-network:

    auth_db:
        container_name: realworld-docker-auth-db
        image: mongo:latest
        volumes:
            - mongodb_auth:/data/db
        networks:
            realworld-docker-network:

    frontend:
        container_name: realworld-docker-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        command: serve -s build -l 3000
        restart: unless-stopped
        networks:
            realworld-docker-network:

    nginx:
        container_name: realworld-docker-nginx
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - frontend
            - api
            - auth
        networks:
            realworld-docker-network:


volumes:
    mongodb_api:
    mongodb_auth:


networks:
    realworld-docker-network:
        driver: bridge
